spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/home_nus_app"
    username: "developer"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

# liquibase:
#   enabled: true
#   change-log:



