spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/home_nus_app"
    username: "developer"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changeset-master.xml



