spring:
  datasource:
#    url: "jdbc:mysql://localhost:3306/home_nus_app"
    url: "jdbc:postgresql://localhost:5432/home_app"
    username: "developer"
    password: "1234qwer0!"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changeset-master.xml

home-application:
  uri:
    root: "http://192.168.84.136"
  q-bit-torrent:
    port: ":10095"
    login:
      uri: "/api/v2/auth/login"
      username: "admin"
      password: "adminadmin"
    uri:
      get-all-data: "/api/v2/sync/maindata"
      delete-torrent: "/api/v2/torrents/delete"
      pause-torrent: "/api/v2/torrents/pause"
      resume-torrent: "/api/v2/torrents/resume"
      download-torrent: "/api/v2/torrents/add"
    request-timeout: 1
    torrent-category:
      root-dataset-media-path: "/media"
      mappings:
        '{
                    "Музыка":"/music",
                    "Видео":"/videos",
                    "Фильм":"/films",
                    "Сериал":"/serials",
                    "Игра":"/games",
                    "Программы":"/program",
                    "Операционные системы":"/os",
                    "Другое":"/other"
          }'
  meTube:
    port: ":10216"
    downloadedPath: "\\\\192.168.84.136\\media"
    quality: "best"
    uri:
      addVideoUri: "/add"

bot:
  name: "home_nas_app_bot"
  token: ""
  file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
  file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"


