spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/home_nus_app"
    username: "developer"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changeset-master.xml

home-application:
  uri:
    root: "http://192.168.0.12"
  qbTorrent:
    port: ":20909"
    uri:
      getAllData: "/api/v2/sync/maindata"
      deleteTorrent: "/api/v2/torrents/delete"
      pauseTorrent: "/api/v2/torrents/pause"
      resumeTorrent: "/api/v2/torrents/resume"
      downloadTorrent: "/api/v2/torrents/add"
    requestTimeout: 1

bot:
  name: "home_nas_app_bot"
  token: ""
  file-info: "https://api.telegram.org/bot{token}/getFile?file_id={fileId}"
  file-storage: "https://api.telegram.org/file/bot{token}/{filePath}"


